workerPoolSpecs:
- machineSpec:
    machineType: "n1-highmem-2"
    acceleratorType: "NVIDIA_TESLA_T4"
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: "gcr.io/chess-transformer/container"
    args:
    - "--job-dir=gcr.io/chess_transformer/models"
